// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: models/proto/chordAdmin/chordAdmin.proto

package chordAdminModel

import (
	context "context"
	chordNodeModel "github.com/NeerajKomuravalli/distributedHashTableGoLangImpl/models/proto/chordNode/chordNodeModel"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *Success) Reset() {
	*x = Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_models_proto_chordAdmin_chordAdmin_proto_rawDescGZIP(), []int{0}
}

func (x *Success) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ActiveNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActiveNodesRequest) Reset() {
	*x = ActiveNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveNodesRequest) ProtoMessage() {}

func (x *ActiveNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveNodesRequest.ProtoReflect.Descriptor instead.
func (*ActiveNodesRequest) Descriptor() ([]byte, []int) {
	return file_models_proto_chordAdmin_chordAdmin_proto_rawDescGZIP(), []int{1}
}

type NumberOfActiveNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NumberOfActiveNodes) Reset() {
	*x = NumberOfActiveNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberOfActiveNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberOfActiveNodes) ProtoMessage() {}

func (x *NumberOfActiveNodes) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberOfActiveNodes.ProtoReflect.Descriptor instead.
func (*NumberOfActiveNodes) Descriptor() ([]byte, []int) {
	return file_models_proto_chordAdmin_chordAdmin_proto_rawDescGZIP(), []int{2}
}

type ActiveNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*chordNodeModel.Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ActiveNodes) Reset() {
	*x = ActiveNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveNodes) ProtoMessage() {}

func (x *ActiveNodes) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveNodes.ProtoReflect.Descriptor instead.
func (*ActiveNodes) Descriptor() ([]byte, []int) {
	return file_models_proto_chordAdmin_chordAdmin_proto_rawDescGZIP(), []int{3}
}

func (x *ActiveNodes) GetNodes() []*chordNodeModel.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type TotalNumberOfNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint64 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (x *TotalNumberOfNodes) Reset() {
	*x = TotalNumberOfNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalNumberOfNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalNumberOfNodes) ProtoMessage() {}

func (x *TotalNumberOfNodes) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalNumberOfNodes.ProtoReflect.Descriptor instead.
func (*TotalNumberOfNodes) Descriptor() ([]byte, []int) {
	return file_models_proto_chordAdmin_chordAdmin_proto_rawDescGZIP(), []int{4}
}

func (x *TotalNumberOfNodes) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_models_proto_chordAdmin_chordAdmin_proto protoreflect.FileDescriptor

var file_models_proto_chordAdmin_chordAdmin_proto_rawDesc = []byte{
	0x0a, 0x28, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x68, 0x6f, 0x72, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x23, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x22, 0x2c, 0x0a, 0x12, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xaa,
	0x01, 0x0a, 0x0a, 0x43, 0x68, 0x6f, 0x72, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x20, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x05,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x08, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x33, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x13, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x18, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x4f, 0x66, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x14, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x13, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x2e,
	0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_proto_chordAdmin_chordAdmin_proto_rawDescOnce sync.Once
	file_models_proto_chordAdmin_chordAdmin_proto_rawDescData = file_models_proto_chordAdmin_chordAdmin_proto_rawDesc
)

func file_models_proto_chordAdmin_chordAdmin_proto_rawDescGZIP() []byte {
	file_models_proto_chordAdmin_chordAdmin_proto_rawDescOnce.Do(func() {
		file_models_proto_chordAdmin_chordAdmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_proto_chordAdmin_chordAdmin_proto_rawDescData)
	})
	return file_models_proto_chordAdmin_chordAdmin_proto_rawDescData
}

var file_models_proto_chordAdmin_chordAdmin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_proto_chordAdmin_chordAdmin_proto_goTypes = []interface{}{
	(*Success)(nil),             // 0: Success
	(*ActiveNodesRequest)(nil),  // 1: ActiveNodesRequest
	(*NumberOfActiveNodes)(nil), // 2: NumberOfActiveNodes
	(*ActiveNodes)(nil),         // 3: ActiveNodes
	(*TotalNumberOfNodes)(nil),  // 4: TotalNumberOfNodes
	(*chordNodeModel.Node)(nil), // 5: Node
}
var file_models_proto_chordAdmin_chordAdmin_proto_depIdxs = []int32{
	5, // 0: ActiveNodes.nodes:type_name -> Node
	5, // 1: ChordAdmin.AddActiveNode:input_type -> Node
	1, // 2: ChordAdmin.GetActiveNodes:input_type -> ActiveNodesRequest
	2, // 3: ChordAdmin.TotalNumberOfActiveNodes:input_type -> NumberOfActiveNodes
	0, // 4: ChordAdmin.AddActiveNode:output_type -> Success
	3, // 5: ChordAdmin.GetActiveNodes:output_type -> ActiveNodes
	4, // 6: ChordAdmin.TotalNumberOfActiveNodes:output_type -> TotalNumberOfNodes
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_proto_chordAdmin_chordAdmin_proto_init() }
func file_models_proto_chordAdmin_chordAdmin_proto_init() {
	if File_models_proto_chordAdmin_chordAdmin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberOfActiveNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_chordAdmin_chordAdmin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalNumberOfNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_proto_chordAdmin_chordAdmin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_proto_chordAdmin_chordAdmin_proto_goTypes,
		DependencyIndexes: file_models_proto_chordAdmin_chordAdmin_proto_depIdxs,
		MessageInfos:      file_models_proto_chordAdmin_chordAdmin_proto_msgTypes,
	}.Build()
	File_models_proto_chordAdmin_chordAdmin_proto = out.File
	file_models_proto_chordAdmin_chordAdmin_proto_rawDesc = nil
	file_models_proto_chordAdmin_chordAdmin_proto_goTypes = nil
	file_models_proto_chordAdmin_chordAdmin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChordAdminClient is the client API for ChordAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChordAdminClient interface {
	AddActiveNode(ctx context.Context, in *chordNodeModel.Node, opts ...grpc.CallOption) (*Success, error)
	GetActiveNodes(ctx context.Context, in *ActiveNodesRequest, opts ...grpc.CallOption) (*ActiveNodes, error)
	TotalNumberOfActiveNodes(ctx context.Context, in *NumberOfActiveNodes, opts ...grpc.CallOption) (*TotalNumberOfNodes, error)
}

type chordAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewChordAdminClient(cc grpc.ClientConnInterface) ChordAdminClient {
	return &chordAdminClient{cc}
}

func (c *chordAdminClient) AddActiveNode(ctx context.Context, in *chordNodeModel.Node, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := c.cc.Invoke(ctx, "/ChordAdmin/AddActiveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordAdminClient) GetActiveNodes(ctx context.Context, in *ActiveNodesRequest, opts ...grpc.CallOption) (*ActiveNodes, error) {
	out := new(ActiveNodes)
	err := c.cc.Invoke(ctx, "/ChordAdmin/GetActiveNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordAdminClient) TotalNumberOfActiveNodes(ctx context.Context, in *NumberOfActiveNodes, opts ...grpc.CallOption) (*TotalNumberOfNodes, error) {
	out := new(TotalNumberOfNodes)
	err := c.cc.Invoke(ctx, "/ChordAdmin/TotalNumberOfActiveNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChordAdminServer is the server API for ChordAdmin service.
type ChordAdminServer interface {
	AddActiveNode(context.Context, *chordNodeModel.Node) (*Success, error)
	GetActiveNodes(context.Context, *ActiveNodesRequest) (*ActiveNodes, error)
	TotalNumberOfActiveNodes(context.Context, *NumberOfActiveNodes) (*TotalNumberOfNodes, error)
}

// UnimplementedChordAdminServer can be embedded to have forward compatible implementations.
type UnimplementedChordAdminServer struct {
}

func (*UnimplementedChordAdminServer) AddActiveNode(context.Context, *chordNodeModel.Node) (*Success, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddActiveNode not implemented")
}
func (*UnimplementedChordAdminServer) GetActiveNodes(context.Context, *ActiveNodesRequest) (*ActiveNodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveNodes not implemented")
}
func (*UnimplementedChordAdminServer) TotalNumberOfActiveNodes(context.Context, *NumberOfActiveNodes) (*TotalNumberOfNodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalNumberOfActiveNodes not implemented")
}

func RegisterChordAdminServer(s *grpc.Server, srv ChordAdminServer) {
	s.RegisterService(&_ChordAdmin_serviceDesc, srv)
}

func _ChordAdmin_AddActiveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(chordNodeModel.Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordAdminServer).AddActiveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChordAdmin/AddActiveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordAdminServer).AddActiveNode(ctx, req.(*chordNodeModel.Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChordAdmin_GetActiveNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordAdminServer).GetActiveNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChordAdmin/GetActiveNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordAdminServer).GetActiveNodes(ctx, req.(*ActiveNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChordAdmin_TotalNumberOfActiveNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberOfActiveNodes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordAdminServer).TotalNumberOfActiveNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChordAdmin/TotalNumberOfActiveNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordAdminServer).TotalNumberOfActiveNodes(ctx, req.(*NumberOfActiveNodes))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChordAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ChordAdmin",
	HandlerType: (*ChordAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddActiveNode",
			Handler:    _ChordAdmin_AddActiveNode_Handler,
		},
		{
			MethodName: "GetActiveNodes",
			Handler:    _ChordAdmin_GetActiveNodes_Handler,
		},
		{
			MethodName: "TotalNumberOfActiveNodes",
			Handler:    _ChordAdmin_TotalNumberOfActiveNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models/proto/chordAdmin/chordAdmin.proto",
}
